# Site settings
title: My Dev Blog
header-img: img/home-bg.png
email: m14868@gmail.com
copyright_name: marineb
description: > # this means to ignore newlines until "baseurl:"
  While I'm Taking The Online Full Stack Bootcamp at Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: marineboudeau
github_username:  marineb
learn_profile: marineb
email_username: m14868@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
